# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

pool:
  vmImage: ubuntu-latest

parameters:
- name: deploymaster
  displayName: Deploy to MASTER
  type: boolean
  default: false

stages:
- stage: build
  jobs:
  - job: Buildmain
    displayName: Build PreRelease
    steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'package'
- stage: deploymaster
  jobs:
  - job: deploymaster
    displayName: Deploy Master
    condition: and(succeeded('build'), eq(${{ parameters.deploymaster }}, true))
    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            # Write your commands here
          
            echo 'Hello world'